:art: refactor to use lib.addCommand
Qbox-project/qbx-weathersync pull request #3
Opened 2023-08-28 22:58 UTC by maejok-xx

## Description

Switches commands from using `QBCore.Commands.Add()` to `lib.addCommand()`

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-08-28 23:15 UTC, Manason requested changes

2023-08-28 23:15 UTC, Manason commented on server/server.lua
> +	restricted = 'admin',
Should this be group.admin instead?

2023-08-28 23:52 UTC, maejok-xx commented on server/server.lua
> +	restricted = 'admin',
Ah, yep, fixed

2023-08-29 15:36 UTC, Manason approved these changes

2023-08-31 23:58 UTC, closed without merging